[package]
name = "pros-rs-3"
version = "0.1.0"
authors = ["Nixon <nixon.emoony@gmail.com>"]
edition = "2018"
license = "MPL-2.0"

[dependencies]
cortex_types = {path="./cortex_types"}

[build-dependencies]
bindgen = "0.51"

[profile.release]
opt-level = 's'
lto = true
